# install:
#  pip3 install pre-commit
# run:
#  pre-commit run --all-files
# update deps:
#  pre-commit autoupdate

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: detect-private-key
      - id: mixed-line-ending
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: fix-byte-order-marker

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-use-type-annotations
      - id: python-no-log-warn
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      - id: text-unicode-replacement-char

#  - repo: https://github.com/Lucas-C/pre-commit-hooks-markup
#    rev: v1.0.1
#    hooks:
#    - id: rst-linter

  - repo: https://github.com/rstcheck/rstcheck
    rev: v6.2.4
    hooks:
      - id: rstcheck
        additional_dependencies: ["rstcheck[sphinx,toml]"]
        args: ["--report-level=WARNING"]  # otherwise there is too much chatter

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.6.3'
    hooks:
      - id: ruff-format
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
