name: QualityAssurance
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Python 🐍
        uses: actions/setup-python@v6
        with:
          python-version: 3.14

      - name: Checkout 🛎️
        uses: actions/checkout@v7

      - name: Run Pre-Commit Tests 🧪
        uses: pre-commit/action@v3.0.1
