name: Release tagged Commit

on:
  workflow_call:
  push:
    # branches: [ main ]  # this is handled as OR (push to main OR tagged)
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  pages: write  # TODO: probably not needed
  id-token: write # TODO: probably not needed

jobs:
  build-pages:
    permissions:
      pages: write
      id-token: write
    uses: ./.github/workflows/sphinx_to_pages.yml
  build-pdf:
    uses: ./.github/workflows/sphinx_to_pdf.yml
  release:
    runs-on: ubuntu-latest
    needs:
      - build-pages
      - build-pdf
    steps:

      - name: Download Artifact PDF
        uses: actions/download-artifact@v4
#        with:
#          name: "Trampolinturnen" # TODO: now all artifacts should be loaded and file is hopefully there

      # TODO: debug
      - name: Display structure of downloaded files
        run: ls -R
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: "./TrampolinTurnen"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: TrampolinTurnen/trampolinturnen.pdf
        if: startsWith(github.ref, 'refs/tags/')
